Added email verification
andrii-doroshenko/nodejs-rest-api pull request #5
Opened 2023-09-10 19:16 UTC by andrii-doroshenko

🚀

2023-09-10 21:24 UTC, ceREAL133 requested changes

2023-09-10 21:24 UTC, ceREAL133 commented on controllers/auth.js
> +      to: email,
separate this const in another file

2023-09-11 20:14 UTC, andrii-doroshenko commented on controllers/auth.js
> +      to: email,
done

2023-09-12 08:38 UTC, ceREAL133 approved these changes

2023-09-12 18:14 UTC, merged